name: LightGenerator
version: '${project.version}'
main: siozy.start.lightgenerator.LightGenerator
author: Siozy
api-version: '1.16'
commands:
  lightgenerator:
    aliases:
      - generator
      - lg
      - lightg
      - lgenerator
depend:
  - LunaSpring
  - SateJewels
  - DecentHolograms
